// languages.js

export const translations = {
  // English Translations
  eng: {
    htmlLang: "en",
    title: "The Smith Family Tragedy: Child Murdered, Body Vanishes",
    headerWorld: "World",
    breadcrumbWorld: "WORLD",
    breadcrumbAmerica: "AMERICAS",
    readTime: "5 MIN READ",
    articleTitle: "The Smith Family Tragedy: Child Murdered, Body Vanishes",
    publishedLabel: "PUBLISHED",
    publishedTime: "March 15, 2010",
    authorPrefix: "By",
    authorName: "CNN Mystery Team",
    imageFigcaption: "A portrait of the Smith family after the departure of their fourth daughter.",
    articleP1: "Jakarta, CNN Indonesia -- A 12-year-old girl was found dead under unnatural circumstances at the Smith family residence in ${lokasi}, on Saturday night (01/17/1924). The victim was identified as ${namaKorban} Smith, the fourth of twelve children. The incident occurred just hours before the family was scheduled for their annual photo session on their porch.",
    articleP2: "According to the police report, ${namaKorban}'s body was found in a gruesome state. Initial suspicions suggest the victim suffered fatal injuries from an attack using a ${alat}. At the scene, officers found an old mask stained with dried blood. Inside the mask, there were scratches resembling an ancient symbol or writing that has not yet been identified.",
    articleP3: "The victim's body was taken to the hospital for an autopsy the next day. However, the procedure failed after the body was reported mysteriously missing. The autopsy table was found empty by the medical team at 6:30 AM. CCTV in the vicinity did not record any activity for seven minutes due to a technical glitch. The only remaining clue was a trail of blood that stopped in the middle of the hospital corridor.",
    articleH2: "Bloody Mask and Suspicions of Mystical Elements",
    articleP4: "The discovery of the mask and the disappearance of the victim's body have fueled speculation about the involvement of mystical elements in the case. The police have not released an official conclusion but stated they have involved experts in symbols and history to analyze the findings at the scene. To date, no suspects or motives have been identified.",
    articleP5: "The Smith family has also refused to provide detailed statements to the media. However, in a brief statement, they said they have fully entrusted the investigation to the competent authorities.",
    articleH3: "Commemorative Photo Session",
    articleP6: "Despite the atmosphere of grief and the lack of legal certainty, the Smith family proceeded with the family photo session to honor the deceased. They were seen leaving a small empty space in the middle of the line as if ${namaKorban} were posing with them.",
    articleP7: "A few days after the photo was printed, reports emerged that a faint silhouette resembling ${namaKorban}'s face appeared in the empty space. There has been no official statement regarding this allegation. However, a family source mentioned that the photo print was not destroyed, although it reportedly caused psychological distress to some family members.",
    articleP8: "This case is still under investigation. The police have stated they will continue to develop their findings to uncover what really happened in the incident that has now become a matter of widespread public attention.",
    relatedTitle: "Read More",
    relatedLink1: "The Most Mysterious Criminal Cases of the 20th Century",
    relatedLink2: "History of Early 20th Century Criminal Psychology",
    relatedLink3: "The Impact of Family Tragedy on Communities",
    searchPlaceholder: "Search CNN...",
    signIn: "Sign in",
    liveTv: "Live TV",
    listen: "Listen",
    watch: "Watch",
    world: "World",
    usPolitics: "US Politics",
    business: "Business",
    markets: "Markets",
    health: "Health",
    entertainment: "Entertainment",
    tech: "Tech",
    style: "Style",
    travel: "Travel",
    followCnn: "FOLLOW CNN",
    termsOfUse: "Terms of Use",
    privacyPolicy: "Privacy Policy",
    cookieSettings: "Cookie Settings",
    adChoices: "Ad Choices",
    accessibility: "Accessibility & CC",
    about: "About",
    newsletters: "Newsletters",
    transcripts: "Transcripts",
    copyright: "© 2025 Cable News Network. A Warner Bros. Discovery Company. All Rights Reserved.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor',
            'b': 'Abigail',
            'c': 'Lillian',
            'd': 'Margaret',
            'e': 'Beatrice',
        },
        lokasiMap: {
            'a': 'the second-floor room',
            'b': 'the attic',
            'c': 'the back shed',
            'd': 'the basement',
            'e': 'the hallway near the kitchen',
        },
        alatMap: {
            'a': 'a knife',
            'b': 'a hammer',
            'c': 'scissors',
            'd': 'a crowbar',
            'e': 'an iron rod',
        }
    }
  },
  // Indonesian Translations
  id: {
    htmlLang: "id",
    title: "Tragedi Keluarga Smith: Anak Dibunuh, Jasadnya Menghilang",
    headerWorld: "Dunia",
    breadcrumbWorld: "DUNIA",
    breadcrumbAmerica: "AMERIKA",
    readTime: "5 MENIT",
    articleTitle: "Tragedi Keluarga Smith: Anak Dibunuh, Jasadnya Menghilang",
    publishedLabel: "DITERBITKAN",
    publishedTime: "15 Maret 2010",
    authorPrefix: "Oleh",
    authorName: "Tim Misteri CNN Indonesia",
    imageFigcaption: "Potret keluarga Smith pasca kepergian putri keempatnya.",
    articleP1: "Jakarta, CNN Indonesia -- Seorang remaja perempuan berusia 12 tahun ditemukan tewas secara tidak wajar di kediaman keluarga Smith, tepatnya di ${lokasi}, Sabtu malam (17/01/1924). Korban diketahui bernama ${namaKorban} Smith, putri keempat dari dua belas bersaudara. Insiden terjadi hanya beberapa jam sebelum keluarga tersebut dijadwalkan menjalani sesi foto tahunan mereka di teras rumah.",
    articleP2: "Menurut laporan kepolisian, jasad ${namaKorban} ditemukan dalam kondisi mengenaskan. Dugaan awal menunjukkan korban mengalami luka fatal akibat serangan menggunakan ${alat}. Di lokasi kejadian, petugas menemukan sebuah topeng tua yang berlumuran darah kering. Pada bagian dalam topeng itu, terdapat goresan menyerupai simbol atau tulisan kuno yang belum dapat diidentifikasi.",
    articleP3: "Jasad korban sempat dibawa ke rumah sakit untuk proses otopsi pada keesokan harinya. Namun proses tersebut gagal dilaksanakan setelah jasad dilaporkan menghilang secara misterius. Meja otopsi ditemukan kosong oleh tim medis pada pukul 06.30 pagi. CCTV di sekitar ruangan tidak merekam aktivitas selama tujuh menit akibat gangguan teknis. Satu-satunya petunjuk yang tersisa adalah jejak darah yang berhenti di tengah lorong rumah sakit.",
    articleH2: "Topeng Berdarah dan Dugaan Unsur Mistis",
    articleP4: "Penemuan topeng dan hilangnya jasad korban memicu dugaan keterlibatan unsur mistis dalam kasus ini. Pihak kepolisian belum merilis kesimpulan resmi, namun menyatakan telah melibatkan pakar simbol dan sejarah untuk menganalisis temuan di lokasi. Hingga saat ini, belum ada tersangka maupun motif yang teridentifikasi.",
    articleP5: "Keluarga Smith juga menolak memberikan keterangan mendetail kepada media. Namun dalam pernyataan singkat, mereka menyatakan telah menyerahkan sepenuhnya penyelidikan kepada otoritas yang berwenang.",
    articleH3: "Sesi Foto Penghormatan",
    articleP6: "Meski dalam suasana duka dan belum mendapat kepastian hukum, keluarga Smith tetap menjalani sesi foto keluarga untuk menghormati mendiang. Terlihat mereka menyisakan sedikit ruang kosong di tengah barisan seolah ${namaKorban} ikut berfoto bersama.",
    articleP7: "Beberapa hari setelah foto dicetak, muncul laporan bahwa siluet samar menyerupai wajah ${namaKorban} tampak di posisi ruang kosong tersebut. Tidak ada keterangan resmi terkait dugaan ini. Namun sumber keluarga menyebutkan bahwa cetakan foto tersebut tidak dimusnahkan meskipun konon menimbulkan gangguan psikologis pada beberapa anggota keluarga.",
    articleP8: "Kasus ini masih dalam tahap penyelidikan. Kepolisian menyatakan akan terus mengembangkan temuan untuk mengungkap apa yang sebenarnya terjadi dalam insiden yang kini menjadi perhatian luas masyarakat.",
    relatedTitle: "Baca Baca",
    relatedLink1: "Kasus Kriminal Paling Misterius di Abad ke-20",
    relatedLink2: "Sejarah Psikologi Kriminal Awal Abad 20",
    relatedLink3: "Dampak Tragedi Keluarga pada Komunitas",
    searchPlaceholder: "Cari CNN...",
    signIn: "Masuk",
    liveTv: "TV Langsung",
    listen: "Dengar",
    watch: "Tonton",
    world: "Dunia",
    usPolitics: "Politik AS",
    business: "Bisnis",
    markets: "Pasar",
    health: "Kesehatan",
    entertainment: "Hiburan",
    tech: "Teknologi",
    style: "Gaya",
    travel: "Wisata",
    followCnn: "IKUTI CNN",
    termsOfUse: "Ketentuan Penggunaan",
    privacyPolicy: "Kebijakan Privasi",
    cookieSettings: "Pengaturan Cookie",
    adChoices: "Pilihan Iklan",
    accessibility: "Aksesibilitas & CC",
    about: "Tentang",
    newsletters: "Buletin",
    transcripts: "Transkrip",
    copyright: "© 2025 Cable News Network. Sebuah Perusahaan Warner Bros. Discovery. Semua Hak Dilindungi Undang-Undang.<br>CNN Sans ™ & © 2016 Cable News Network.",
    articleParams: {
        namaKorbanMap: {
            'a': 'Eleanor',
            'b': 'Abigail',
            'c': 'Lillian',
            'd': 'Margaret',
            'e': 'Beatrice',
        },
        lokasiMap: {
            'a': 'kamar lantai dua',
            'b': 'loteng',
            'c': 'gudang belakang',
            'd': 'ruang bawah tanah',
            'e': 'lorong dekat dapur',
        },
        alatMap: {
            'a': 'pisau',
            'b': 'palu',
            'c': 'gunting',
            'd': 'linggis',
            'e': 'batang besi',
        }
    }
  }
};